export const servicesData = {
    "in-room-dining": {
      title: "In-Room Dining",
      items: [
        {
          title: "Classic Caesar Salad",
          description: "Crisp romaine lettuce, parmesan cheese, croutons, and our house-made Caesar dressing",
          price: 450,
          nutritionalInfo: { calories: 350, protein: 10, carbs: 15, fat: 28 },
          weight: 200,
          images: ["/placeholder.svg?height=200&width=200"],
          dietaryInfo: { vegetarian: true },
          allergens: [
            { name: "Milk", icon: "milk" },
            { name: "Eggs", icon: "egg" },
          ],
          origin: "Italian cuisine",
          relatedItems: ["Grilled Chicken Breast", "Tomato Soup"],
        },
        {
          title: "Margherita Pizza",
          description: "Classic pizza with tomato sauce, fresh mozzarella, and basil",
          price: 550,
          nutritionalInfo: { calories: 800, protein: 24, carbs: 90, fat: 36 },
          weight: 400,
          images: ["/placeholder.svg?height=200&width=200"],
          dietaryInfo: { vegetarian: true },
          allergens: [
            { name: "Gluten", icon: "wheat" },
            { name: "Milk", icon: "milk" },
          ],
          origin: "Italian cuisine",
          relatedItems: ["Pepperoni Pizza", "Garlic Bread"],
        },
        {
          title: "Grilled Salmon",
          description: "Fresh salmon fillet grilled to perfection, served with steamed vegetables and lemon butter sauce",
          price: 850,
          nutritionalInfo: { calories: 520, protein: 40, carbs: 10, fat: 35 },
          weight: 300,
          images: ["/placeholder.svg?height=200&width=200"],
          dietaryInfo: { glutenFree: true },
          allergens: [{ name: "Fish", icon: "fish" }],
          origin: "International cuisine",
          relatedItems: ["Grilled Chicken Breast", "Steamed Vegetables"],
        },
      ],
    },
    "spa-massage": {
      title: "Spa & Massage",
      items: [
        {
          title: "Swedish Massage",
          description: "A classic full-body massage to relax and ease tension",
          price: 2500,
          duration: 60,
          images: ["https://images.unsplash.com/photo-1598901986949-f593ff2a31a6?q=80&w=2097&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
          benefits: ["Stress relief", "Improved circulation", "Muscle relaxation"],
          relatedServices: ["Deep Tissue Massage", "Aromatherapy Massage"],
        },
        {
          title: "Hot Stone Therapy",
          description: "Heated stones are used to melt away tension and promote deep relaxation",
          price: 3000,
          duration: 90,
          images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNx7-4JAg-bBRH9OKeNsBys5LVhcqdVwbIov27stXW6iVW3Bg8pHnsr614_nknu5PTt5M&usqp=CAU"],
          benefits: ["Deep muscle relaxation", "Improved sleep", "Reduced stress"],
          relatedServices: ["Swedish Massage", "Aromatherapy Massage"],
        },
        {
          title: "Aromatherapy Facial",
          description: "A soothing facial treatment using essential oils to nourish and rejuvenate your skin",
          price: 2000,
          duration: 45,
          images: ["https://images.hindi.news18.com/ibnkhabar/uploads/2021/10/shutterstock_179371097.jpg"],
          benefits: ["Skin hydration", "Relaxation", "Improved skin tone"],
          relatedServices: ["Swedish Massage", "Manicure & Pedicure"],
        },
      ],
    },
    "tour-travel": {
      title: "Tour & Travel",
      items: [
        {
          title: "City Sightseeing Tour",
          description: "Explore the city's main attractions with a knowledgeable guide",
          price: 1500,
          duration: 240,
          images: ["/placeholder.svg?height=200&width=200"],
          highlights: ["Visit to historical landmarks", "Local market exploration", "Photo opportunities"],
          includes: ["Transportation", "Guide", "Bottled water"],
          relatedTours: ["Cultural Heritage Tour", "Food Tasting Tour"],
        },
        {
          title: "Nature Trail Hike",
          description: "A guided hike through scenic nature trails and lush forests",
          price: 2000,
          duration: 300,
          images: ["/placeholder.svg?height=200&width=200"],
          highlights: ["Breathtaking views", "Wildlife spotting", "Natural landmarks"],
          includes: ["Transportation", "Guide", "Packed lunch", "First-aid kit"],
          relatedTours: ["Bird Watching Tour", "Waterfall Trek"],
        },
        {
          title: "Cultural Heritage Tour",
          description: "Immerse yourself in the local culture and traditions",
          price: 1800,
          duration: 270,
          images: ["/placeholder.svg?height=200&width=200"],
          highlights: ["Visit to ancient temples", "Traditional dance performance", "Artisan workshops"],
          includes: ["Transportation", "Guide", "Entrance fees", "Traditional snacks"],
          relatedTours: ["City Sightseeing Tour", "Food Tasting Tour"],
        },
      ],
    },
  }
  
  